"""initial schema

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-05-14 22:00:00.000000+00:00

Hand-written (not autogenerated) — autogenerate needs a live DB connection
and we want this committable before the first docker-compose up. The
schema mirrors shared/db_models exactly. After this migration is applied
once, future schema changes can use autogenerate against the running DB.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # === calls ==============================================================
    op.create_table(
        "calls",
        sa.Column("id", sa.UUID(as_uuid=False), primary_key=True, nullable=False),
        sa.Column("client_ip", postgresql.INET(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="in_progress"),
        sa.Column("visitor_name", sa.String(length=255), nullable=True),
        sa.Column("project_brief", sa.Text(), nullable=True),
        sa.Column("fit_score", sa.String(length=20), nullable=True),
        sa.Column("fit_reasoning", sa.Text(), nullable=True),
        sa.Column("action_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("discord_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_calls_client_ip", "calls", ["client_ip"])
    op.create_index("ix_calls_expires_at", "calls", ["expires_at"])
    op.create_index("ix_calls_client_ip_started", "calls", ["client_ip", "started_at"])

    # === call_messages ======================================================
    op.create_table(
        "call_messages",
        sa.Column("id", sa.UUID(as_uuid=False), primary_key=True, nullable=False),
        sa.Column("call_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ts_offset_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_call_messages_call_id", "call_messages", ["call_id"])

    # === call_artifacts =====================================================
    op.create_table(
        "call_artifacts",
        sa.Column("id", sa.UUID(as_uuid=False), primary_key=True, nullable=False),
        sa.Column("call_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("download_token", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("download_token"),
    )
    op.create_index("ix_call_artifacts_call_id", "call_artifacts", ["call_id"])
    op.create_index(
        "ix_call_artifacts_download_token",
        "call_artifacts",
        ["download_token"],
    )

    # === knowledge_documents ================================================
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.UUID(as_uuid=False), primary_key=True, nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column("page_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tag", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("last_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_table("knowledge_documents")
    op.drop_index("ix_call_artifacts_download_token", table_name="call_artifacts")
    op.drop_index("ix_call_artifacts_call_id", table_name="call_artifacts")
    op.drop_table("call_artifacts")
    op.drop_index("ix_call_messages_call_id", table_name="call_messages")
    op.drop_table("call_messages")
    op.drop_index("ix_calls_client_ip_started", table_name="calls")
    op.drop_index("ix_calls_expires_at", table_name="calls")
    op.drop_index("ix_calls_client_ip", table_name="calls")
    op.drop_table("calls")
